apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert --controller deployment --out ml-predict.yml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: predictor
    name: predictor
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    selector:
      io.kompose.service: predictor
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert --controller deployment --out ml-predict.yml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: predictor
    name: predictor
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: predictor
      spec:
        containers:
        - image: florianseidel/ml-microservice:latest
          name: predictor
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

